version: '3.0'

services:
  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
    - .:/usr/src/app/${BOT_NAME:-tg_bot}
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    networks:
    - tg_bot


  my_redis:
    image: redis:7.0.5-alpine
    container_name: "REDIS-2"
    restart: always
    networks:
      - tg_bot
    ports:
      - '127.0.0.1:6380:6380/tcp'


networks:
  tg_bot:
    driver: bridge
